### ISSUE TITLE
Unable to run `UniVPNCS`

### ISSUE THREAD

**Issue by ffahead** [jesusdf/huawei-vpn#1]
I want to run UniVPN using CLI, but after running `/usr/local/UniVPN/serviceclient/UniVPNCS` I get the following error:
```
[ DOPRA  INFO   XXXX-XX-XX XX:XX:XX ][root][ddm log init][UniVPNCS, start log number is 0, pid is X]
[ CEPS   ERROR  XXXX-XX-XX XX:XX:XX ][root][XXXXXXXXXXXX][PUB Chown Owner][get  pwd failed]
```

**Comment by jesusdf** [comment]
Sorry but this docker is not running yet. I started the development but haven't had time to finish it yet. Moreover, the Huawei VPN hardware also supports using a standard IPSec VPN gateway, so I followed that path for my use case.

I will update the README.md file to let anyone know this.
